# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 670)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tagList = QtWidgets.QListWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagList.sizePolicy().hasHeightForWidth())
        self.tagList.setSizePolicy(sizePolicy)
        self.tagList.setMinimumSize(QtCore.QSize(0, 0))
        self.tagList.setAutoFillBackground(False)
        self.tagList.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.tagList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tagList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tagList.setUniformItemSizes(True)
        self.tagList.setObjectName("tagList")
        self.verticalLayout.addWidget(self.tagList)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tagsModeDropdown = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagsModeDropdown.sizePolicy().hasHeightForWidth())
        self.tagsModeDropdown.setSizePolicy(sizePolicy)
        self.tagsModeDropdown.setObjectName("tagsModeDropdown")
        self.gridLayout_2.addWidget(self.tagsModeDropdown, 1, 0, 1, 4)
        self.tagsInvertButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagsInvertButton.sizePolicy().hasHeightForWidth())
        self.tagsInvertButton.setSizePolicy(sizePolicy)
        self.tagsInvertButton.setMinimumSize(QtCore.QSize(50, 0))
        self.tagsInvertButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tagsInvertButton.setObjectName("tagsInvertButton")
        self.gridLayout_2.addWidget(self.tagsInvertButton, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.tagsAllButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagsAllButton.sizePolicy().hasHeightForWidth())
        self.tagsAllButton.setSizePolicy(sizePolicy)
        self.tagsAllButton.setMinimumSize(QtCore.QSize(50, 0))
        self.tagsAllButton.setObjectName("tagsAllButton")
        self.gridLayout_2.addWidget(self.tagsAllButton, 0, 2, 1, 1)
        self.tagsNoneButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagsNoneButton.sizePolicy().hasHeightForWidth())
        self.tagsNoneButton.setSizePolicy(sizePolicy)
        self.tagsNoneButton.setMinimumSize(QtCore.QSize(50, 0))
        self.tagsNoneButton.setObjectName("tagsNoneButton")
        self.gridLayout_2.addWidget(self.tagsNoneButton, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchBox = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBox.sizePolicy().hasHeightForWidth())
        self.searchBox.setSizePolicy(sizePolicy)
        self.searchBox.setObjectName("searchBox")
        self.horizontalLayout_3.addWidget(self.searchBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.splitter = QtWidgets.QSplitter(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.bookmarkTable = QtWidgets.QTableView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.bookmarkTable.sizePolicy().hasHeightForWidth())
        self.bookmarkTable.setSizePolicy(sizePolicy)
        self.bookmarkTable.setTabKeyNavigation(False)
        self.bookmarkTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.bookmarkTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.bookmarkTable.setSortingEnabled(True)
        self.bookmarkTable.setObjectName("bookmarkTable")
        self.bookmarkTable.horizontalHeader().setDefaultSectionSize(250)
        self.bookmarkTable.horizontalHeader().setHighlightSections(False)
        self.bookmarkTable.horizontalHeader().setStretchLastSection(True)
        self.bookmarkTable.verticalHeader().setVisible(False)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.nameBox = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameBox.sizePolicy().hasHeightForWidth())
        self.nameBox.setSizePolicy(sizePolicy)
        self.nameBox.setObjectName("nameBox")
        self.gridLayout.addWidget(self.nameBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.urlBox = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlBox.sizePolicy().hasHeightForWidth())
        self.urlBox.setSizePolicy(sizePolicy)
        self.urlBox.setObjectName("urlBox")
        self.horizontalLayout.addWidget(self.urlBox)
        self.copyUrlButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.copyUrlButton.setObjectName("copyUrlButton")
        self.horizontalLayout.addWidget(self.copyUrlButton)
        self.browseUrlButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.browseUrlButton.setObjectName("browseUrlButton")
        self.horizontalLayout.addWidget(self.browseUrlButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.tagsBox = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagsBox.sizePolicy().hasHeightForWidth())
        self.tagsBox.setSizePolicy(sizePolicy)
        self.tagsBox.setObjectName("tagsBox")
        self.gridLayout.addWidget(self.tagsBox, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.privateCheck = QtWidgets.QCheckBox(self.layoutWidget2)
        self.privateCheck.setObjectName("privateCheck")
        self.gridLayout.addWidget(self.privateCheck, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.descriptionBox = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.descriptionBox.sizePolicy().hasHeightForWidth())
        self.descriptionBox.setSizePolicy(sizePolicy)
        self.descriptionBox.setTabChangesFocus(True)
        self.descriptionBox.setObjectName("descriptionBox")
        self.gridLayout.addWidget(self.descriptionBox, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout_2.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuBookmark = QtWidgets.QMenu(self.menubar)
        self.menuBookmark.setObjectName("menuBookmark")
        self.menuTag = QtWidgets.QMenu(self.menubar)
        self.menuTag.setObjectName("menuTag")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.action_Quit = QtWidgets.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionNew_from_clipboard = QtWidgets.QAction(MainWindow)
        self.actionNew_from_clipboard.setObjectName("actionNew_from_clipboard")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionDeleteTag = QtWidgets.QAction(MainWindow)
        self.actionDeleteTag.setObjectName("actionDeleteTag")
        self.actionRenameTag = QtWidgets.QAction(MainWindow)
        self.actionRenameTag.setObjectName("actionRenameTag")
        self.actionMerge_into = QtWidgets.QAction(MainWindow)
        self.actionMerge_into.setObjectName("actionMerge_into")
        self.actionWayBack = QtWidgets.QAction(MainWindow)
        self.actionWayBack.setObjectName("actionWayBack")
        self.actionNew_database = QtWidgets.QAction(MainWindow)
        self.actionNew_database.setObjectName("actionNew_database")
        self.actionOpen_database = QtWidgets.QAction(MainWindow)
        self.actionOpen_database.setObjectName("actionOpen_database")
        self.actionImport_CSV = QtWidgets.QAction(MainWindow)
        self.actionImport_CSV.setObjectName("actionImport_CSV")
        self.actionExport_CSV = QtWidgets.QAction(MainWindow)
        self.actionExport_CSV.setObjectName("actionExport_CSV")
        self.actionShowPrivate = QtWidgets.QAction(MainWindow)
        self.actionShowPrivate.setCheckable(True)
        self.actionShowPrivate.setObjectName("actionShowPrivate")
        self.actionHide_Private_Items = QtWidgets.QAction(MainWindow)
        self.actionHide_Private_Items.setObjectName("actionHide_Private_Items")
        self.actionContens = QtWidgets.QAction(MainWindow)
        self.actionContens.setObjectName("actionContens")
        self.actionAbout_RabbitMark = QtWidgets.QAction(MainWindow)
        self.actionAbout_RabbitMark.setObjectName("actionAbout_RabbitMark")
        self.actionReport_Bug = QtWidgets.QAction(MainWindow)
        self.actionReport_Bug.setObjectName("actionReport_Bug")
        self.actionCopyUrl = QtWidgets.QAction(MainWindow)
        self.actionCopyUrl.setObjectName("actionCopyUrl")
        self.actionBrowseToUrl = QtWidgets.QAction(MainWindow)
        self.actionBrowseToUrl.setObjectName("actionBrowseToUrl")
        self.menu_File.addAction(self.actionNew_database)
        self.menu_File.addAction(self.actionOpen_database)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionShowPrivate)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionImport_CSV)
        self.menu_File.addAction(self.actionExport_CSV)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menuBookmark.addAction(self.actionNew)
        self.menuBookmark.addAction(self.actionNew_from_clipboard)
        self.menuBookmark.addSeparator()
        self.menuBookmark.addAction(self.actionWayBack)
        self.menuBookmark.addAction(self.actionDelete)
        self.menuBookmark.addSeparator()
        self.menuBookmark.addAction(self.actionCopyUrl)
        self.menuBookmark.addAction(self.actionBrowseToUrl)
        self.menuTag.addAction(self.actionRenameTag)
        self.menuTag.addAction(self.actionMerge_into)
        self.menuTag.addAction(self.actionDeleteTag)
        self.menu_Help.addAction(self.actionContens)
        self.menu_Help.addAction(self.actionReport_Bug)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.actionAbout_RabbitMark)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuBookmark.menuAction())
        self.menubar.addAction(self.menuTag.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.label_2.setBuddy(self.nameBox)
        self.label_3.setBuddy(self.urlBox)
        self.label_4.setBuddy(self.tagsBox)
        self.label_5.setBuddy(self.descriptionBox)
        self.label_6.setBuddy(self.privateCheck)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tagList, self.tagsNoneButton)
        MainWindow.setTabOrder(self.tagsNoneButton, self.tagsAllButton)
        MainWindow.setTabOrder(self.tagsAllButton, self.tagsInvertButton)
        MainWindow.setTabOrder(self.tagsInvertButton, self.tagsModeDropdown)
        MainWindow.setTabOrder(self.tagsModeDropdown, self.searchBox)
        MainWindow.setTabOrder(self.searchBox, self.bookmarkTable)
        MainWindow.setTabOrder(self.bookmarkTable, self.nameBox)
        MainWindow.setTabOrder(self.nameBox, self.urlBox)
        MainWindow.setTabOrder(self.urlBox, self.tagsBox)
        MainWindow.setTabOrder(self.tagsBox, self.descriptionBox)
        MainWindow.setTabOrder(self.descriptionBox, self.privateCheck)
        MainWindow.setTabOrder(self.privateCheck, self.copyUrlButton)
        MainWindow.setTabOrder(self.copyUrlButton, self.browseUrlButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RabbitMark"))
        self.tagsInvertButton.setText(_translate("MainWindow", "Invert"))
        self.label.setText(_translate("MainWindow", " Select:"))
        self.tagsAllButton.setText(_translate("MainWindow", "All"))
        self.tagsNoneButton.setText(_translate("MainWindow", "None"))
        self.searchBox.setPlaceholderText(_translate("MainWindow", "Filter... (Ctrl+F)"))
        self.label_2.setText(_translate("MainWindow", "&Name"))
        self.label_3.setText(_translate("MainWindow", "&URL"))
        self.copyUrlButton.setToolTip(_translate("MainWindow", "Shortcut: Ctrl-Shift-C"))
        self.copyUrlButton.setText(_translate("MainWindow", "&Copy"))
        self.browseUrlButton.setToolTip(_translate("MainWindow", "Shortcut: Ctrl-B"))
        self.browseUrlButton.setText(_translate("MainWindow", "&Browse to"))
        self.label_4.setText(_translate("MainWindow", "&Tags"))
        self.label_5.setText(_translate("MainWindow", "&Description"))
        self.privateCheck.setText(_translate("MainWindow", "&Private"))
        self.label_6.setText(_translate("MainWindow", "Flags"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menuBookmark.setTitle(_translate("MainWindow", "Book&mark"))
        self.menuTag.setTitle(_translate("MainWindow", "Ta&g"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.action_Quit.setText(_translate("MainWindow", "&Quit"))
        self.action_Quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionDelete.setText(_translate("MainWindow", "&Delete"))
        self.actionDelete.setToolTip(_translate("MainWindow", "Permanently delete the currently selected bookmark."))
        self.actionDelete.setShortcut(_translate("MainWindow", "Ctrl+Shift+Del"))
        self.actionNew_from_clipboard.setText(_translate("MainWindow", "New from Cli&pboard"))
        self.actionNew_from_clipboard.setToolTip(_translate("MainWindow", "Create a new bookmark, pasting your clipboard as the URL."))
        self.actionNew_from_clipboard.setShortcut(_translate("MainWindow", "Ctrl+Shift+N"))
        self.actionNew.setText(_translate("MainWindow", "&New"))
        self.actionNew.setToolTip(_translate("MainWindow", "Create a new bookmark."))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionDeleteTag.setText(_translate("MainWindow", "&Delete"))
        self.actionDeleteTag.setShortcut(_translate("MainWindow", "Ctrl+Alt+Shift+Del"))
        self.actionRenameTag.setText(_translate("MainWindow", "&Rename..."))
        self.actionRenameTag.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionMerge_into.setText(_translate("MainWindow", "&Merge Into..."))
        self.actionMerge_into.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionWayBack.setText(_translate("MainWindow", "Find in &WayBackMachine..."))
        self.actionWayBack.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionNew_database.setText(_translate("MainWindow", "New..."))
        self.actionNew_database.setShortcut(_translate("MainWindow", "Ctrl+Alt+N"))
        self.actionOpen_database.setText(_translate("MainWindow", "Open..."))
        self.actionOpen_database.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionImport_CSV.setText(_translate("MainWindow", "Import CSV..."))
        self.actionExport_CSV.setText(_translate("MainWindow", "Export CSV..."))
        self.actionShowPrivate.setText(_translate("MainWindow", "Show Private Items"))
        self.actionShowPrivate.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionHide_Private_Items.setText(_translate("MainWindow", "Hide Private Items"))
        self.actionContens.setText(_translate("MainWindow", "&Contents"))
        self.actionContens.setShortcut(_translate("MainWindow", "F1"))
        self.actionAbout_RabbitMark.setText(_translate("MainWindow", "&About RabbitMark"))
        self.actionReport_Bug.setText(_translate("MainWindow", "Report &Bug"))
        self.actionCopyUrl.setText(_translate("MainWindow", "&Copy URL"))
        self.actionCopyUrl.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionBrowseToUrl.setText(_translate("MainWindow", "&Browse to URL"))
        self.actionBrowseToUrl.setShortcut(_translate("MainWindow", "Ctrl+B"))

