#!/bin/bash

if [ ! -d "designer" ]; then
    echo "This script must be run from the project's root directory."
    exit
fi

mkdir -p forms

#packageInit='forms/__init__.py'
#echo "# -*- coding: utf-8 -*-" > $packageInit
#echo "# This file is automatically generated by designer/makeForms.sh." >> $packageInit
#echo -e "# WARNING! All changes made in this file will be lost!\n" >> $packageInit

didUpdate=0
for i in designer/*.ui
do
    moduleName=$(basename $i .ui)
    if [ $i -nt forms/$moduleName.py ]; then
        didUpdate=1
        echo "Updating: $moduleName"
        pyuic5 $i -o rabbitmark/forms/$moduleName.py
    fi
    #echo "import $moduleName" >> $packageInit
done

if [ $didUpdate != 1 ]; then
    echo "No forms to update."
fi
