# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/bookmark_details.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(582, 293)
        Form.setBaseSize(QtCore.QSize(600, 200))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.nameBox = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameBox.sizePolicy().hasHeightForWidth())
        self.nameBox.setSizePolicy(sizePolicy)
        self.nameBox.setObjectName("nameBox")
        self.gridLayout.addWidget(self.nameBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.urlBox = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlBox.sizePolicy().hasHeightForWidth())
        self.urlBox.setSizePolicy(sizePolicy)
        self.urlBox.setObjectName("urlBox")
        self.horizontalLayout.addWidget(self.urlBox)
        self.copyUrlButton = QtWidgets.QPushButton(Form)
        self.copyUrlButton.setObjectName("copyUrlButton")
        self.horizontalLayout.addWidget(self.copyUrlButton)
        self.browseUrlButton = QtWidgets.QPushButton(Form)
        self.browseUrlButton.setObjectName("browseUrlButton")
        self.horizontalLayout.addWidget(self.browseUrlButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.tagsBox = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagsBox.sizePolicy().hasHeightForWidth())
        self.tagsBox.setSizePolicy(sizePolicy)
        self.tagsBox.setObjectName("tagsBox")
        self.gridLayout.addWidget(self.tagsBox, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.descriptionBox = QtWidgets.QPlainTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.descriptionBox.sizePolicy().hasHeightForWidth())
        self.descriptionBox.setSizePolicy(sizePolicy)
        self.descriptionBox.setTabChangesFocus(True)
        self.descriptionBox.setObjectName("descriptionBox")
        self.gridLayout.addWidget(self.descriptionBox, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.privateCheck = QtWidgets.QCheckBox(Form)
        self.privateCheck.setObjectName("privateCheck")
        self.horizontalLayout_2.addWidget(self.privateCheck)
        self.linkcheckCheck = QtWidgets.QCheckBox(Form)
        self.linkcheckCheck.setObjectName("linkcheckCheck")
        self.horizontalLayout_2.addWidget(self.linkcheckCheck)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        self.label_2.setBuddy(self.nameBox)
        self.label_3.setBuddy(self.urlBox)
        self.label_4.setBuddy(self.tagsBox)
        self.label_5.setBuddy(self.descriptionBox)
        self.label_6.setBuddy(self.privateCheck)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.nameBox, self.urlBox)
        Form.setTabOrder(self.urlBox, self.tagsBox)
        Form.setTabOrder(self.tagsBox, self.descriptionBox)
        Form.setTabOrder(self.descriptionBox, self.privateCheck)
        Form.setTabOrder(self.privateCheck, self.linkcheckCheck)
        Form.setTabOrder(self.linkcheckCheck, self.copyUrlButton)
        Form.setTabOrder(self.copyUrlButton, self.browseUrlButton)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "&Name"))
        self.label_3.setText(_translate("Form", "&URL"))
        self.copyUrlButton.setToolTip(_translate("Form", "Shortcut: Ctrl-Shift-C"))
        self.copyUrlButton.setText(_translate("Form", "&Copy"))
        self.browseUrlButton.setToolTip(_translate("Form", "Shortcut: Ctrl-B"))
        self.browseUrlButton.setText(_translate("Form", "&Browse to"))
        self.label_4.setText(_translate("Form", "&Tags"))
        self.label_5.setText(_translate("Form", "&Description"))
        self.label_6.setText(_translate("Form", "Flags"))
        self.privateCheck.setText(_translate("Form", "&Private"))
        self.linkcheckCheck.setText(_translate("Form", "Skip linkcheck"))

