# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/linkcheck.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(754, 531)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.pageList = QtWidgets.QListWidget(self.layoutWidget)
        self.pageList.setObjectName("pageList")
        self.verticalLayout_2.addWidget(self.pageList)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.statusCodeBox = QtWidgets.QLineEdit(self.groupBox_2)
        self.statusCodeBox.setReadOnly(True)
        self.statusCodeBox.setObjectName("statusCodeBox")
        self.gridLayout.addWidget(self.statusCodeBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.detailsBox = QtWidgets.QLineEdit(self.groupBox_2)
        self.detailsBox.setReadOnly(True)
        self.detailsBox.setObjectName("detailsBox")
        self.gridLayout.addWidget(self.detailsBox, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.detailsWidget = QtWidgets.QWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detailsWidget.sizePolicy().hasHeightForWidth())
        self.detailsWidget.setSizePolicy(sizePolicy)
        self.detailsWidget.setObjectName("detailsWidget")
        self.gridLayout_2.addWidget(self.detailsWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wayBackMachineButton = QtWidgets.QPushButton(self.groupBox)
        self.wayBackMachineButton.setObjectName("wayBackMachineButton")
        self.horizontalLayout_2.addWidget(self.wayBackMachineButton)
        self.deleteButton = QtWidgets.QPushButton(self.groupBox)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_2.addWidget(self.deleteButton)
        self.dismissButton = QtWidgets.QPushButton(self.groupBox)
        self.dismissButton.setObjectName("dismissButton")
        self.horizontalLayout_2.addWidget(self.dismissButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.closeButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.splitter)
        self.label.setBuddy(self.statusCodeBox)
        self.label_2.setBuddy(self.detailsBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.wayBackMachineButton, self.deleteButton)
        Dialog.setTabOrder(self.deleteButton, self.dismissButton)
        Dialog.setTabOrder(self.dismissButton, self.closeButton)
        Dialog.setTabOrder(self.closeButton, self.pageList)
        Dialog.setTabOrder(self.pageList, self.statusCodeBox)
        Dialog.setTabOrder(self.statusCodeBox, self.detailsBox)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Review Broken Links"))
        self.label_6.setText(_translate("Dialog", "The following pages were not accessible:"))
        self.groupBox_2.setTitle(_translate("Dialog", "Error details"))
        self.label.setText(_translate("Dialog", "HTTP status code"))
        self.label_2.setText(_translate("Dialog", "Details"))
        self.groupBox_3.setTitle(_translate("Dialog", "Bookmark"))
        self.groupBox.setTitle(_translate("Dialog", "Actions"))
        self.wayBackMachineButton.setToolTip(_translate("Dialog", "Try to find a WayBackMachine snapshot for this bookmark."))
        self.wayBackMachineButton.setText(_translate("Dialog", "Find in &WayBackMachine"))
        self.deleteButton.setToolTip(_translate("Dialog", "Delete this bookmark completely."))
        self.deleteButton.setText(_translate("Dialog", "&Delete"))
        self.dismissButton.setToolTip(_translate("Dialog", "Mark this item as checked and remove it from the list."))
        self.dismissButton.setText(_translate("Dialog", "Di&smiss"))
        self.closeButton.setText(_translate("Dialog", "Close"))

