# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 670)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tagList = QtWidgets.QListWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagList.sizePolicy().hasHeightForWidth())
        self.tagList.setSizePolicy(sizePolicy)
        self.tagList.setMinimumSize(QtCore.QSize(0, 0))
        self.tagList.setAutoFillBackground(False)
        self.tagList.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.tagList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tagList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tagList.setUniformItemSizes(True)
        self.tagList.setObjectName("tagList")
        self.verticalLayout.addWidget(self.tagList)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tagsModeDropdown = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagsModeDropdown.sizePolicy().hasHeightForWidth())
        self.tagsModeDropdown.setSizePolicy(sizePolicy)
        self.tagsModeDropdown.setObjectName("tagsModeDropdown")
        self.gridLayout_2.addWidget(self.tagsModeDropdown, 1, 0, 1, 4)
        self.tagsInvertButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagsInvertButton.sizePolicy().hasHeightForWidth())
        self.tagsInvertButton.setSizePolicy(sizePolicy)
        self.tagsInvertButton.setMinimumSize(QtCore.QSize(50, 0))
        self.tagsInvertButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tagsInvertButton.setObjectName("tagsInvertButton")
        self.gridLayout_2.addWidget(self.tagsInvertButton, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.tagsAllButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagsAllButton.sizePolicy().hasHeightForWidth())
        self.tagsAllButton.setSizePolicy(sizePolicy)
        self.tagsAllButton.setMinimumSize(QtCore.QSize(50, 0))
        self.tagsAllButton.setObjectName("tagsAllButton")
        self.gridLayout_2.addWidget(self.tagsAllButton, 0, 2, 1, 1)
        self.tagsNoneButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagsNoneButton.sizePolicy().hasHeightForWidth())
        self.tagsNoneButton.setSizePolicy(sizePolicy)
        self.tagsNoneButton.setMinimumSize(QtCore.QSize(50, 0))
        self.tagsNoneButton.setObjectName("tagsNoneButton")
        self.gridLayout_2.addWidget(self.tagsNoneButton, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.bookmarksLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.bookmarksLayout.setContentsMargins(0, 0, 0, 0)
        self.bookmarksLayout.setObjectName("bookmarksLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchBox = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBox.sizePolicy().hasHeightForWidth())
        self.searchBox.setSizePolicy(sizePolicy)
        self.searchBox.setClearButtonEnabled(True)
        self.searchBox.setObjectName("searchBox")
        self.horizontalLayout_3.addWidget(self.searchBox)
        self.bookmarksLayout.addLayout(self.horizontalLayout_3)
        self.splitter = QtWidgets.QSplitter(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.bookmarkTable = QtWidgets.QTableView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.bookmarkTable.sizePolicy().hasHeightForWidth())
        self.bookmarkTable.setSizePolicy(sizePolicy)
        self.bookmarkTable.setTabKeyNavigation(False)
        self.bookmarkTable.setAlternatingRowColors(True)
        self.bookmarkTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.bookmarkTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.bookmarkTable.setGridStyle(QtCore.Qt.NoPen)
        self.bookmarkTable.setObjectName("bookmarkTable")
        self.bookmarkTable.horizontalHeader().setDefaultSectionSize(250)
        self.bookmarkTable.horizontalHeader().setHighlightSections(False)
        self.bookmarkTable.verticalHeader().setVisible(False)
        self.detailsWidget = QtWidgets.QWidget(self.splitter)
        self.detailsWidget.setObjectName("detailsWidget")
        self.bookmarksLayout.addWidget(self.splitter)
        self.horizontalLayout_2.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuBookmark = QtWidgets.QMenu(self.menubar)
        self.menuBookmark.setObjectName("menuBookmark")
        self.menuTag = QtWidgets.QMenu(self.menubar)
        self.menuTag.setObjectName("menuTag")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.action_Quit = QtWidgets.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionNew_from_clipboard = QtWidgets.QAction(MainWindow)
        self.actionNew_from_clipboard.setObjectName("actionNew_from_clipboard")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionDeleteTag = QtWidgets.QAction(MainWindow)
        self.actionDeleteTag.setObjectName("actionDeleteTag")
        self.actionRenameTag = QtWidgets.QAction(MainWindow)
        self.actionRenameTag.setObjectName("actionRenameTag")
        self.actionMergeTag = QtWidgets.QAction(MainWindow)
        self.actionMergeTag.setObjectName("actionMergeTag")
        self.actionWayBack = QtWidgets.QAction(MainWindow)
        self.actionWayBack.setObjectName("actionWayBack")
        self.actionNew_database = QtWidgets.QAction(MainWindow)
        self.actionNew_database.setObjectName("actionNew_database")
        self.actionOpen_database = QtWidgets.QAction(MainWindow)
        self.actionOpen_database.setObjectName("actionOpen_database")
        self.actionImport_CSV = QtWidgets.QAction(MainWindow)
        self.actionImport_CSV.setObjectName("actionImport_CSV")
        self.actionExport_CSV = QtWidgets.QAction(MainWindow)
        self.actionExport_CSV.setObjectName("actionExport_CSV")
        self.actionShowPrivate = QtWidgets.QAction(MainWindow)
        self.actionShowPrivate.setCheckable(True)
        self.actionShowPrivate.setObjectName("actionShowPrivate")
        self.actionHide_Private_Items = QtWidgets.QAction(MainWindow)
        self.actionHide_Private_Items.setObjectName("actionHide_Private_Items")
        self.actionContents = QtWidgets.QAction(MainWindow)
        self.actionContents.setObjectName("actionContents")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionReportBug = QtWidgets.QAction(MainWindow)
        self.actionReportBug.setObjectName("actionReportBug")
        self.actionCopyUrl = QtWidgets.QAction(MainWindow)
        self.actionCopyUrl.setObjectName("actionCopyUrl")
        self.actionBrowseToUrl = QtWidgets.QAction(MainWindow)
        self.actionBrowseToUrl.setObjectName("actionBrowseToUrl")
        self.actionBrokenLinks = QtWidgets.QAction(MainWindow)
        self.actionBrokenLinks.setObjectName("actionBrokenLinks")
        self.actionSendToPocket = QtWidgets.QAction(MainWindow)
        self.actionSendToPocket.setObjectName("actionSendToPocket")
        self.actionSnapshotSite = QtWidgets.QAction(MainWindow)
        self.actionSnapshotSite.setObjectName("actionSnapshotSite")
        self.actionImportFromPocket = QtWidgets.QAction(MainWindow)
        self.actionImportFromPocket.setObjectName("actionImportFromPocket")
        self.menu_File.addAction(self.actionNew_database)
        self.menu_File.addAction(self.actionOpen_database)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionShowPrivate)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionImport_CSV)
        self.menu_File.addAction(self.actionExport_CSV)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menuBookmark.addAction(self.actionNew)
        self.menuBookmark.addAction(self.actionNew_from_clipboard)
        self.menuBookmark.addSeparator()
        self.menuBookmark.addAction(self.actionWayBack)
        self.menuBookmark.addAction(self.actionDelete)
        self.menuBookmark.addSeparator()
        self.menuBookmark.addAction(self.actionCopyUrl)
        self.menuBookmark.addAction(self.actionBrowseToUrl)
        self.menuBookmark.addAction(self.actionSendToPocket)
        self.menuBookmark.addAction(self.actionSnapshotSite)
        self.menuTag.addAction(self.actionRenameTag)
        self.menuTag.addAction(self.actionMergeTag)
        self.menuTag.addAction(self.actionDeleteTag)
        self.menu_Help.addAction(self.actionContents)
        self.menu_Help.addAction(self.actionReportBug)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.actionAbout)
        self.menuTools.addAction(self.actionBrokenLinks)
        self.menuTools.addAction(self.actionImportFromPocket)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuBookmark.menuAction())
        self.menubar.addAction(self.menuTag.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tagList, self.tagsNoneButton)
        MainWindow.setTabOrder(self.tagsNoneButton, self.tagsAllButton)
        MainWindow.setTabOrder(self.tagsAllButton, self.tagsInvertButton)
        MainWindow.setTabOrder(self.tagsInvertButton, self.tagsModeDropdown)
        MainWindow.setTabOrder(self.tagsModeDropdown, self.searchBox)
        MainWindow.setTabOrder(self.searchBox, self.bookmarkTable)
        MainWindow.setTabOrder(self.bookmarkTable, self.detailsWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RabbitMark"))
        self.tagsInvertButton.setText(_translate("MainWindow", "Invert"))
        self.label.setText(_translate("MainWindow", " Select:"))
        self.tagsAllButton.setText(_translate("MainWindow", "All"))
        self.tagsNoneButton.setText(_translate("MainWindow", "None"))
        self.searchBox.setPlaceholderText(_translate("MainWindow", "Filter... (Ctrl+F)"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menuBookmark.setTitle(_translate("MainWindow", "Book&mark"))
        self.menuTag.setTitle(_translate("MainWindow", "Ta&g"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menuTools.setTitle(_translate("MainWindow", "T&ools"))
        self.action_Quit.setText(_translate("MainWindow", "&Quit"))
        self.action_Quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionDelete.setText(_translate("MainWindow", "&Delete"))
        self.actionDelete.setToolTip(_translate("MainWindow", "Permanently delete the currently selected bookmark."))
        self.actionDelete.setShortcut(_translate("MainWindow", "Ctrl+Shift+Del"))
        self.actionNew_from_clipboard.setText(_translate("MainWindow", "New from Cli&pboard"))
        self.actionNew_from_clipboard.setToolTip(_translate("MainWindow", "Create a new bookmark, pasting your clipboard as the URL."))
        self.actionNew_from_clipboard.setShortcut(_translate("MainWindow", "Ctrl+Shift+N"))
        self.actionNew.setText(_translate("MainWindow", "&New"))
        self.actionNew.setToolTip(_translate("MainWindow", "Create a new bookmark."))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionDeleteTag.setText(_translate("MainWindow", "&Delete"))
        self.actionDeleteTag.setShortcut(_translate("MainWindow", "Ctrl+Alt+Shift+Del"))
        self.actionRenameTag.setText(_translate("MainWindow", "&Rename..."))
        self.actionRenameTag.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionMergeTag.setText(_translate("MainWindow", "&Merge Into..."))
        self.actionMergeTag.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionWayBack.setText(_translate("MainWindow", "Find in &WayBackMachine..."))
        self.actionWayBack.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionNew_database.setText(_translate("MainWindow", "New..."))
        self.actionNew_database.setShortcut(_translate("MainWindow", "Ctrl+Alt+N"))
        self.actionOpen_database.setText(_translate("MainWindow", "Open..."))
        self.actionOpen_database.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionImport_CSV.setText(_translate("MainWindow", "Import CSV..."))
        self.actionImport_CSV.setShortcut(_translate("MainWindow", "Ctrl+Shift+I"))
        self.actionExport_CSV.setText(_translate("MainWindow", "Export CSV..."))
        self.actionExport_CSV.setShortcut(_translate("MainWindow", "Ctrl+Shift+E"))
        self.actionShowPrivate.setText(_translate("MainWindow", "Show Private Items"))
        self.actionShowPrivate.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionHide_Private_Items.setText(_translate("MainWindow", "Hide Private Items"))
        self.actionContents.setText(_translate("MainWindow", "&Contents"))
        self.actionContents.setShortcut(_translate("MainWindow", "F1"))
        self.actionAbout.setText(_translate("MainWindow", "&About RabbitMark"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Shift+F1"))
        self.actionReportBug.setText(_translate("MainWindow", "Report &Bug"))
        self.actionCopyUrl.setText(_translate("MainWindow", "&Copy URL"))
        self.actionCopyUrl.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionBrowseToUrl.setText(_translate("MainWindow", "&Browse to URL"))
        self.actionBrowseToUrl.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionBrokenLinks.setText(_translate("MainWindow", "Find &Broken Links..."))
        self.actionBrokenLinks.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionSendToPocket.setText(_translate("MainWindow", "Send to &Pocket..."))
        self.actionSendToPocket.setShortcut(_translate("MainWindow", "Ctrl+K"))
        self.actionSnapshotSite.setText(_translate("MainWindow", "&Request WayBackMachine Snapshot"))
        self.actionSnapshotSite.setShortcut(_translate("MainWindow", "Ctrl+Shift+W"))
        self.actionImportFromPocket.setText(_translate("MainWindow", "Import from &Pocket..."))
        self.actionImportFromPocket.setShortcut(_translate("MainWindow", "Ctrl+Shift+K"))

